---
## GITPOD SETTINGS

# here are the automated tasks.

tasks:
  - name: install R
# the | symbol allows multiple line actions
# action1
# action2
    init: |
      #from https://cran.r-project.org/bin/linux/ubuntu/
      # update indices
      sudo apt update -qq
      # install two helper packages we need
      sudo apt install  --assume-yes --no-install-recommends software-properties-common dirmngr
      # add the signing key (by Michael Rutter) for these repos
      # To verify key, run gpg --show-keys /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc 
      # Fingerprint: 298A3A825C0D65DFD57CBB651716619E084DAB9
      wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | sudo tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc
      # add the R 4.0 repo from CRAN -- adjust 'focal' to 'groovy' or 'bionic' as needed
      sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
      sudo apt install  --assume-yes --no-install-recommends r-base
      sudo add-apt-repository ppa:c2d4u.team/c2d4u4.0+
      sudo apt install  --assume-yes --no-install-recommends r-cran-rstan r-cran-tidyverse


# here are the extensions
vscode:
  extensions:
    - Ikuyadeu.r
    - RDebugger.r-debugger
    - anwar.papyrus-pdf
    - mhutchie.git-graph
